// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ns.proto

package com.vitessedata.llql.llql_proto;

public final class LLQLNs {
  private LLQLNs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code llql_proto.Namespace}
   */
  public enum Namespace
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LLQL = 0;</code>
     */
    LLQL(0, 0),
    /**
     * <code>Postgres = 1;</code>
     */
    Postgres(1, 1),
    ;

    /**
     * <code>LLQL = 0;</code>
     */
    public static final int LLQL_VALUE = 0;
    /**
     * <code>Postgres = 1;</code>
     */
    public static final int Postgres_VALUE = 1;


    public final int getNumber() { return value; }

    public static Namespace valueOf(int value) {
      switch (value) {
        case 0: return LLQL;
        case 1: return Postgres;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Namespace>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Namespace>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Namespace>() {
            public Namespace findValueByNumber(int number) {
              return Namespace.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.vitessedata.llql.llql_proto.LLQLNs.getDescriptor().getEnumTypes().get(0);
    }

    private static final Namespace[] VALUES = values();

    public static Namespace valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Namespace(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:llql_proto.Namespace)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010ns.proto\022\nllql_proto*#\n\tNamespace\022\010\n\004L" +
      "LQL\020\000\022\014\n\010Postgres\020\001B)\n\037com.vitessedata.l" +
      "lql.llql_protoB\006LLQLNs"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
