// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: err.proto

package com.vitessedata.llql.llql_proto;

public final class LLQLError {
  private LLQLError() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code llql_proto.ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EC_OK = 0;</code>
     */
    EC_OK(0, 0),
    /**
     * <code>EC_STOP = 1;</code>
     */
    EC_STOP(1, 1),
    /**
     * <code>EC_RUNTIME_ERROR = 2;</code>
     */
    EC_RUNTIME_ERROR(2, 2),
    /**
     * <code>EC_JIT_INIT_FAILED = 100;</code>
     */
    EC_JIT_INIT_FAILED(3, 100),
    /**
     * <code>EC_JIT_FAILED = 101;</code>
     */
    EC_JIT_FAILED(4, 101),
    /**
     * <code>EC_OUT_OF_RESOURCE = 1000;</code>
     */
    EC_OUT_OF_RESOURCE(5, 1000),
    /**
     * <code>EC_OUT_OF_MEMORY = 1001;</code>
     */
    EC_OUT_OF_MEMORY(6, 1001),
    /**
     * <code>EC_BAD_MSG = 2000;</code>
     */
    EC_BAD_MSG(7, 2000),
    /**
     * <code>EC_BAD_MSG_CHKSUM = 2001;</code>
     */
    EC_BAD_MSG_CHKSUM(8, 2001),
    /**
     * <code>EC_QUERY_NOT_REGISTERED = 2002;</code>
     */
    EC_QUERY_NOT_REGISTERED(9, 2002),
    /**
     * <code>EC_OBSOLETE = 2003;</code>
     */
    EC_OBSOLETE(10, 2003),
    /**
     * <code>EC_NETWORK_ERROR = 3000;</code>
     */
    EC_NETWORK_ERROR(11, 3000),
    /**
     * <code>EC_CSV_PARSING_ERROR = 4000;</code>
     */
    EC_CSV_PARSING_ERROR(12, 4000),
    /**
     * <code>EC_INT_PARSING_ERROR = 4001;</code>
     */
    EC_INT_PARSING_ERROR(13, 4001),
    /**
     * <code>EC_FLOAT_PARSING_ERROR = 4002;</code>
     */
    EC_FLOAT_PARSING_ERROR(14, 4002),
    /**
     * <code>EC_NYI = 1000000;</code>
     */
    EC_NYI(15, 1000000),
    /**
     * <code>EC_TEST_WRONG_RESULT = 1000001;</code>
     */
    EC_TEST_WRONG_RESULT(16, 1000001),
    ;

    /**
     * <code>EC_OK = 0;</code>
     */
    public static final int EC_OK_VALUE = 0;
    /**
     * <code>EC_STOP = 1;</code>
     */
    public static final int EC_STOP_VALUE = 1;
    /**
     * <code>EC_RUNTIME_ERROR = 2;</code>
     */
    public static final int EC_RUNTIME_ERROR_VALUE = 2;
    /**
     * <code>EC_JIT_INIT_FAILED = 100;</code>
     */
    public static final int EC_JIT_INIT_FAILED_VALUE = 100;
    /**
     * <code>EC_JIT_FAILED = 101;</code>
     */
    public static final int EC_JIT_FAILED_VALUE = 101;
    /**
     * <code>EC_OUT_OF_RESOURCE = 1000;</code>
     */
    public static final int EC_OUT_OF_RESOURCE_VALUE = 1000;
    /**
     * <code>EC_OUT_OF_MEMORY = 1001;</code>
     */
    public static final int EC_OUT_OF_MEMORY_VALUE = 1001;
    /**
     * <code>EC_BAD_MSG = 2000;</code>
     */
    public static final int EC_BAD_MSG_VALUE = 2000;
    /**
     * <code>EC_BAD_MSG_CHKSUM = 2001;</code>
     */
    public static final int EC_BAD_MSG_CHKSUM_VALUE = 2001;
    /**
     * <code>EC_QUERY_NOT_REGISTERED = 2002;</code>
     */
    public static final int EC_QUERY_NOT_REGISTERED_VALUE = 2002;
    /**
     * <code>EC_OBSOLETE = 2003;</code>
     */
    public static final int EC_OBSOLETE_VALUE = 2003;
    /**
     * <code>EC_NETWORK_ERROR = 3000;</code>
     */
    public static final int EC_NETWORK_ERROR_VALUE = 3000;
    /**
     * <code>EC_CSV_PARSING_ERROR = 4000;</code>
     */
    public static final int EC_CSV_PARSING_ERROR_VALUE = 4000;
    /**
     * <code>EC_INT_PARSING_ERROR = 4001;</code>
     */
    public static final int EC_INT_PARSING_ERROR_VALUE = 4001;
    /**
     * <code>EC_FLOAT_PARSING_ERROR = 4002;</code>
     */
    public static final int EC_FLOAT_PARSING_ERROR_VALUE = 4002;
    /**
     * <code>EC_NYI = 1000000;</code>
     */
    public static final int EC_NYI_VALUE = 1000000;
    /**
     * <code>EC_TEST_WRONG_RESULT = 1000001;</code>
     */
    public static final int EC_TEST_WRONG_RESULT_VALUE = 1000001;


    public final int getNumber() { return value; }

    public static ErrorCode valueOf(int value) {
      switch (value) {
        case 0: return EC_OK;
        case 1: return EC_STOP;
        case 2: return EC_RUNTIME_ERROR;
        case 100: return EC_JIT_INIT_FAILED;
        case 101: return EC_JIT_FAILED;
        case 1000: return EC_OUT_OF_RESOURCE;
        case 1001: return EC_OUT_OF_MEMORY;
        case 2000: return EC_BAD_MSG;
        case 2001: return EC_BAD_MSG_CHKSUM;
        case 2002: return EC_QUERY_NOT_REGISTERED;
        case 2003: return EC_OBSOLETE;
        case 3000: return EC_NETWORK_ERROR;
        case 4000: return EC_CSV_PARSING_ERROR;
        case 4001: return EC_INT_PARSING_ERROR;
        case 4002: return EC_FLOAT_PARSING_ERROR;
        case 1000000: return EC_NYI;
        case 1000001: return EC_TEST_WRONG_RESULT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.vitessedata.llql.llql_proto.LLQLError.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ErrorCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:llql_proto.ErrorCode)
  }

  public interface ErrorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .llql_proto.ErrorCode ec = 1;
    /**
     * <code>required .llql_proto.ErrorCode ec = 1;</code>
     */
    boolean hasEc();
    /**
     * <code>required .llql_proto.ErrorCode ec = 1;</code>
     */
    com.vitessedata.llql.llql_proto.LLQLError.ErrorCode getEc();

    // required string msg = 2;
    /**
     * <code>required string msg = 2;</code>
     */
    boolean hasMsg();
    /**
     * <code>required string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>required string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code llql_proto.Error}
   */
  public static final class Error extends
      com.google.protobuf.GeneratedMessage
      implements ErrorOrBuilder {
    // Use Error.newBuilder() to construct.
    private Error(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Error(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Error defaultInstance;
    public static Error getDefaultInstance() {
      return defaultInstance;
    }

    public Error getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Error(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.vitessedata.llql.llql_proto.LLQLError.ErrorCode value = com.vitessedata.llql.llql_proto.LLQLError.ErrorCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                ec_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vitessedata.llql.llql_proto.LLQLError.internal_static_llql_proto_Error_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vitessedata.llql.llql_proto.LLQLError.internal_static_llql_proto_Error_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vitessedata.llql.llql_proto.LLQLError.Error.class, com.vitessedata.llql.llql_proto.LLQLError.Error.Builder.class);
    }

    public static com.google.protobuf.Parser<Error> PARSER =
        new com.google.protobuf.AbstractParser<Error>() {
      public Error parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Error(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Error> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .llql_proto.ErrorCode ec = 1;
    public static final int EC_FIELD_NUMBER = 1;
    private com.vitessedata.llql.llql_proto.LLQLError.ErrorCode ec_;
    /**
     * <code>required .llql_proto.ErrorCode ec = 1;</code>
     */
    public boolean hasEc() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .llql_proto.ErrorCode ec = 1;</code>
     */
    public com.vitessedata.llql.llql_proto.LLQLError.ErrorCode getEc() {
      return ec_;
    }

    // required string msg = 2;
    public static final int MSG_FIELD_NUMBER = 2;
    private java.lang.Object msg_;
    /**
     * <code>required string msg = 2;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      ec_ = com.vitessedata.llql.llql_proto.LLQLError.ErrorCode.EC_OK;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasEc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, ec_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, ec_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.vitessedata.llql.llql_proto.LLQLError.Error parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vitessedata.llql.llql_proto.LLQLError.Error parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vitessedata.llql.llql_proto.LLQLError.Error parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vitessedata.llql.llql_proto.LLQLError.Error parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vitessedata.llql.llql_proto.LLQLError.Error parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.vitessedata.llql.llql_proto.LLQLError.Error parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.vitessedata.llql.llql_proto.LLQLError.Error parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.vitessedata.llql.llql_proto.LLQLError.Error parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.vitessedata.llql.llql_proto.LLQLError.Error parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.vitessedata.llql.llql_proto.LLQLError.Error parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.vitessedata.llql.llql_proto.LLQLError.Error prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code llql_proto.Error}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.vitessedata.llql.llql_proto.LLQLError.ErrorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vitessedata.llql.llql_proto.LLQLError.internal_static_llql_proto_Error_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vitessedata.llql.llql_proto.LLQLError.internal_static_llql_proto_Error_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vitessedata.llql.llql_proto.LLQLError.Error.class, com.vitessedata.llql.llql_proto.LLQLError.Error.Builder.class);
      }

      // Construct using com.vitessedata.llql.llql_proto.LLQLError.Error.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ec_ = com.vitessedata.llql.llql_proto.LLQLError.ErrorCode.EC_OK;
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vitessedata.llql.llql_proto.LLQLError.internal_static_llql_proto_Error_descriptor;
      }

      public com.vitessedata.llql.llql_proto.LLQLError.Error getDefaultInstanceForType() {
        return com.vitessedata.llql.llql_proto.LLQLError.Error.getDefaultInstance();
      }

      public com.vitessedata.llql.llql_proto.LLQLError.Error build() {
        com.vitessedata.llql.llql_proto.LLQLError.Error result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.vitessedata.llql.llql_proto.LLQLError.Error buildPartial() {
        com.vitessedata.llql.llql_proto.LLQLError.Error result = new com.vitessedata.llql.llql_proto.LLQLError.Error(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ec_ = ec_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vitessedata.llql.llql_proto.LLQLError.Error) {
          return mergeFrom((com.vitessedata.llql.llql_proto.LLQLError.Error)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vitessedata.llql.llql_proto.LLQLError.Error other) {
        if (other == com.vitessedata.llql.llql_proto.LLQLError.Error.getDefaultInstance()) return this;
        if (other.hasEc()) {
          setEc(other.getEc());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000002;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEc()) {
          
          return false;
        }
        if (!hasMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.vitessedata.llql.llql_proto.LLQLError.Error parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.vitessedata.llql.llql_proto.LLQLError.Error) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .llql_proto.ErrorCode ec = 1;
      private com.vitessedata.llql.llql_proto.LLQLError.ErrorCode ec_ = com.vitessedata.llql.llql_proto.LLQLError.ErrorCode.EC_OK;
      /**
       * <code>required .llql_proto.ErrorCode ec = 1;</code>
       */
      public boolean hasEc() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .llql_proto.ErrorCode ec = 1;</code>
       */
      public com.vitessedata.llql.llql_proto.LLQLError.ErrorCode getEc() {
        return ec_;
      }
      /**
       * <code>required .llql_proto.ErrorCode ec = 1;</code>
       */
      public Builder setEc(com.vitessedata.llql.llql_proto.LLQLError.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        ec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .llql_proto.ErrorCode ec = 1;</code>
       */
      public Builder clearEc() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ec_ = com.vitessedata.llql.llql_proto.LLQLError.ErrorCode.EC_OK;
        onChanged();
        return this;
      }

      // required string msg = 2;
      private java.lang.Object msg_ = "";
      /**
       * <code>required string msg = 2;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:llql_proto.Error)
    }

    static {
      defaultInstance = new Error(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:llql_proto.Error)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_llql_proto_Error_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llql_proto_Error_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\terr.proto\022\nllql_proto\"7\n\005Error\022!\n\002ec\030\001" +
      " \002(\0162\025.llql_proto.ErrorCode\022\013\n\003msg\030\002 \002(\t" +
      "*\201\003\n\tErrorCode\022\t\n\005EC_OK\020\000\022\013\n\007EC_STOP\020\001\022\024" +
      "\n\020EC_RUNTIME_ERROR\020\002\022\026\n\022EC_JIT_INIT_FAIL" +
      "ED\020d\022\021\n\rEC_JIT_FAILED\020e\022\027\n\022EC_OUT_OF_RES" +
      "OURCE\020\350\007\022\025\n\020EC_OUT_OF_MEMORY\020\351\007\022\017\n\nEC_BA" +
      "D_MSG\020\320\017\022\026\n\021EC_BAD_MSG_CHKSUM\020\321\017\022\034\n\027EC_Q" +
      "UERY_NOT_REGISTERED\020\322\017\022\020\n\013EC_OBSOLETE\020\323\017" +
      "\022\025\n\020EC_NETWORK_ERROR\020\270\027\022\031\n\024EC_CSV_PARSIN" +
      "G_ERROR\020\240\037\022\031\n\024EC_INT_PARSING_ERROR\020\241\037\022\033\n",
      "\026EC_FLOAT_PARSING_ERROR\020\242\037\022\014\n\006EC_NYI\020\300\204=" +
      "\022\032\n\024EC_TEST_WRONG_RESULT\020\301\204=B,\n\037com.vite" +
      "ssedata.llql.llql_protoB\tLLQLError"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_llql_proto_Error_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_llql_proto_Error_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_llql_proto_Error_descriptor,
              new java.lang.String[] { "Ec", "Msg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
